name: Deploy React to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/hado-global-service
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # Install dependencies & build React
            npm install
            npm run build

            # Deploy build files to Apache
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/hado-global-service/dist/spa/* /var/www/html/

            # Restart Apache
            sudo systemctl restart apache2

            # 🔹 Renew SSL (safe to run anytime, only renews if needed)
            sudo certbot renew --quiet
            sudo systemctl reload apache2
